<div class="fiscal-code-calculator-modal">

    <button id="fiscal-code-calculator-close">
        X
    </button>

    <div id="fiscal-code-calculator">
        <form autocomplete="off">
            <div class="cdf-form-control control-firstname">
                <label class="block-label">Nome <input name="firstname" class="form-control name" type="text"/></label>
            </div>

            <div class="cdf-form-control control-lastname">
                <label class="block-label">Cognome <input name="lastname" class="form-control lastname"
                                                          type="text"/></label>
            </div>

            <div class="cdf-form-control control-common">
                <label class="block-label">Città <input autocomplete="off" name="common"
                                                        class="form-control common fcd-common"
                                                        type="text"/></label>

                <div class="commons-hint">

                </div>
            </div>

            <div class="cdf-form-control control-date">
                <label class="control-day">
                    Giorno nascita
                    <select name="day" class="day">
                        <option>-</option>
                        <?php foreach (range(1, 31) as $day) : ?>
                            <option value="<?php echo sprintf("%02d", $day); ?>"><?php echo sprintf("%02d", $day); ?></option>
                        <?php endforeach; ?>
                    </select>
                </label>
                &nbsp;
                <label class="control-month">
                    Mese nascita
                    <select name="month" class="month">
                        <option>-</option>
                        <?php foreach (range(1, 12) as $day) : ?>
                            <option value="<?php echo sprintf("%02d", $day); ?>"><?php echo sprintf("%02d", $day); ?></option>
                        <?php endforeach; ?>
                    </select>
                </label>
                &nbsp;
                <label class="control-year">
                    Anno nascita
                    <select name="year" class="year">
                        <option>-</option>
                        <?php foreach (range(1930, date("Y")) as $day) : ?>
                            <option value="<?php echo $day; ?>"><?php echo $day; ?></option>
                        <?php endforeach; ?>
                    </select>
                </label>
            </div>

            <div class="cdf-form-control control-gender">
                <label class="block-label">
                    Sesso
                </label>
                <div>
                    <!--                    <label>-->
                    <!--                        M <input type="radio" name="gender" value="M" class="form-control gender">-->
                    <!--                    </label>-->
                    <!--                    <label>-->
                    <!--                        F <input type="radio" name="gender" value="F" class="form-control gender">-->
                    <!--                    </label>-->
                    <select name="gender" class="form-control gender">
                        <option>-</option>
                        <option value="M">M</option>
                        <option value="F">F</option>
                    </select>
                </div>
            </div>

            <button class="submit">Calcola</button>
        </form>
    </div>
</div>