<?php
$fiscalCodeSelector = $this->getData('fiscal_code_selector');
?>


<button id="fiscal-code-calculator-open" data-fiscal-code-selector="<?php echo $fiscalCodeSelector; ?>" type="button">Calcola codice fiscale</button>


<link rel="stylesheet" href="/skin/frontend/base/default/capimichi/calcolocodicefiscale/css/calcolocodicefiscale.css">
<link rel="stylesheet" href="/skin/frontend/base/default/capimichi/calcolocodicefiscale/css/jquery.modal.min.css">

<script src="/js/capimichi/calcolocodicefiscale/jquery.modal.min.js"></script>
<script src="/js/capimichi/calcolocodicefiscale/calculator.js"></script>