<?php
$fiscalCodeSelector = $this->getData('fiscal_code_selector');
$submitButtonSelector = $this->getData('submit_button_selector');
?>

<div id="fiscal-code-checker" data-fiscal-code-selector="<?php echo $fiscalCodeSelector; ?>"
     data-submit-button-selector="<?php echo $submitButtonSelector; ?>"></div>

<link rel="stylesheet" href="/skin/frontend/base/default/capimichi/calcolocodicefiscale/css/calcolocodicefiscale.css">
<link rel="stylesheet" href="/skin/frontend/base/default/capimichi/calcolocodicefiscale/css/jquery.modal.min.css">

<script src="/js/capimichi/calcolocodicefiscale/jquery.modal.min.js"></script>
<script src="/js/capimichi/calcolocodicefiscale/checker.js"></script>